type: python_app
src_dir: libs/ubitool
main_file: ubitool/main.py
tmux_session:
    debug:
        name: appcon2
        cwd: libs/ubitool
    console: 
        name: appcon2
        cwd: libs/ubitool
external_description_files:
    - libs/ai_coding/configs/libs/ubitool/description.rst
